version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build:ci

artifacts:
  files:
    - '**/*.html'
    - '**/*.js'
    - '**/*.ts'
    - '**/*.css'
    - '**/*.ico'
  discard-paths: yes
  base-directory: 'dist/public'