version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.8.1
  pre_build:
    commands:
      - npm install
      - npm install @angular/cli -g
  build:
    commands:
      - npm run build:ci